title: GIOVANNI MAFFEI Ph.D.
url: "https://giovannimaffei.github.io"
baseurl: "/personal_test/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: ""
footer_text: "CC Giovanni Maffei (2018) - Original design by Ankit Sultana "

sass:
    style: compressed
    sass_dir: _sass
